export const GET_ERRORS = "GET_ERRORS";
// export const SET_ERRORS = "SET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const STOP_USER_LOADING = "STOP_USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const EDIT_CURRENT_USER = 'EDIT_CURRENT_USER';

export const GET_ARTICLES = 'GET_ARTICLES';
export const POST_ARTICLE = 'POST_ARTICLE';
export const LOADING_ARTICLE = 'LOADING_ARTICLE';
export const STOP_ARTICLE_LOADING = 'STOP_ARTICLE_LOADING';

export const INC_LIKE = 'INC_LIKE';
export const DEC_LIKE = 'DEC_LIKE';